enabled_backends = ["arch", "cargo", "flatpak"]
hostname_groups_enabled = true

[arch]
package_manager = "paru"

[flatpak]
systemwide = true

[hostname_groups]
"pingu" = [
    "base",
    "audio",
    "desktop-environment",
    "programs/cli",
    "programs/general",
    "programs/gaming",
    "programs/development",
    "programs/development-plus",
    "programs/office",
    "programs/testing",
    "programs/media",
    "games/general",
    "games/roblox",
    "games/minecraft",
    "hosts/pingu",
]
"real-huawei-chromebook" = [
    "base",
    "audio",
    "desktop-environment",
    "programs/cli",
    "programs/general",
    "programs/office",
    "programs/school",
    "programs/development",
    "hosts/real-huawei-chromebook",
]
