arch = [
    "base",
    "linux",
    "linux-firmware",
    "base-devel", # many things need base-devel even if this isn't strictly a development environment

    # booting
    "grub",
    "efibootmgr",

    # networking
    "networkmanager",
    "nm-connection-editor",

    # general utilities
    "sudo",
    "paru",
    "git",
    "stow",
    "rustup",
]

cargo = [
    "metapac"
]
