arch = [
    "niri",
    "qt5-wayland",
    "kitty",
    "wl-clipboard",
    "xdg-desktop-portal",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-wlr",
    "xdg-desktop-portal-gnome",
    "gnome-keyring",
    "adwaita-qt5-git",
    "adwaita-qt6-git",
    "swaylock",
    "lemurs",
    "kanshi",

    # services
    "polkit-kde-agent",
    "xwayland-satellite",
    "swww",
    "swaync",
    "swayidle",

    # IME
    "fcitx5",
    "fcitx5-configtool",
    "fcitx5-pinyin-zhwiki",
    "fcitx5-chinese-addons",

    # fonts
    "noto-fonts",
    "noto-fonts-cjk",
    "noto-fonts-emoji",
    "ttf-jetbrains-mono",

    # shell
    "rofi",
    "rofimoji",
    "rofi-calc",

    # shell: eww compilation dependencies
    # we are compiling eww from scratch
    "gtk3",
    "gtk-layer-shell",
    "pango",
    "gdk-pixbuf2",
    "libdbusmenu-gtk3",
    "cairo",
    "glib2",
    "gcc-libs",
    "glibc",
]
