arch = [
    "amd-ucode",
    "vulkan-radeon",
    "os-prober", # dual booting Windows
    "ntfs-3g",
    "proton-vpn-gtk-app",

    # graphics tablet
    { package = "opentabletdriver", hooks = { after_install = ["bash", "-c", "sudo mkinitcpio -P; sudo rmmod wacom; systemctl --user add-wants niri.service opentabletdriver.service;"] } }
]
